# Generated by Django 4.1 on 2022-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('ФАРА', 'фара'), ('РЕШЁТКА', 'решётка'), ('РУЧКА', 'ручка'), ('КАПОТ', 'капот'), ('РУЛЬ', 'руль'), ('КРЕСЛО', 'кресло')], max_length=255, verbose_name='Auto detail')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('parameter', models.TextField(blank=True, max_length=250, verbose_name='Parameters')),
            ],
        ),
    ]
