# Generated by Django 4.1 on 2022-08-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='quantity',
        ),
    ]
