# Generated by Django 4.1 on 2022-08-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_factory', '0002_remove_detail_parameter_remove_detail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail_type',
            field=models.CharField(choices=[('ФАРА', 'фара'), ('РЕШЁТКА', 'решётка'), ('РУЧКА', 'ручка'), ('КАПОТ', 'капот'), ('РУЛЬ', 'руль'), ('КРЕСЛО', 'кресло')], max_length=255, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='CurrentAutoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('parameter', models.TextField(blank=True, max_length=250, verbose_name='Parameters')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_factory.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('markup', models.FloatField(default=0, verbose_name='Наценка')),
                ('parts', models.ManyToManyField(to='app_factory.currentautodetail')),
            ],
        ),
    ]
